#+title: Emacs startup config

* Using this setup

  The easiest way to use this config is to clone this repo to your
  =$HOME/.emacs.d= directory.
  
  #+BEGIN_EXAMPLE
  git clone https://github.com/dmj111/emacs.d ~/.emacs.d
  #+END_EXAMPLE

  
** Customizing

   You can customize this startup without changing any of the files
   from this repository.  
   
   To do so, create a =.emacs.d/local= directory.  In that directory,
   optionally create =init-local.el= and =init-local-preload.el=.
   =init-local-preload.el= is loaded early in the setup, and
   =init-local.el= is loaded towards the end.

   If you want to create custom snippet files, they go in
   =local/snippets=.

   You can create a git repo inside the local directory if you wish to
   control the local customizations.

* Trying this setup
  To try out this file without actually installing it, run:

#+BEGIN_EXAMPLE
  emacs -nw -L . -l init.el
#+END_EXAMPLE

 - =-nw= no window
 - =-L .= add . to search path
 - =-l init.el= run init.el
 - =-Q= (maybe?  quick)

* References
  - [[https://github.com/bbatsov/prelude][Emacs Prelude]]
  - [[https://github.com/purcell/emacs.d][Steve Purcell's startup]]

* Notes


Universal arg: C-u is shorthand for 4.
C-u C-u is 4 times 4

C-0 to 9, and M-0 to 9 are bound to those numbers

C--, M--, C-M-- are negative, and can reverse the direction of a
command.


M-x eval-buffer, eval-region
C-M-x - eval-defun

C-h i to run info

- [, ] to go back/forward

ESC ESC ESC - close prompts, everything, goes back to one window.

C-/ - undo

#+BEGIN_EXAMPLE

  file local header:
     -*- mode: mode-name-here; my-variable: value -*-

  footer:
  Local Variables:
  mode: mode-name-here
  my-variable: value
  End:
#+END_EXAMPLE

- auto-mode-alist
- magic-mode-alist


- C-h C <RET> -- see current encoding system
- 



C-x 0 delete active window
C-x 1 delete other windows


Looks useful for S-left/right, etc:
(windmove-default-keybindings)

Other window commands:
C-x 4
- C-f (open file)
- d dired
- C-o displays buffer
- switches to buffer and window
- kills buffer and window

C-x 5: frame commands
2 - create new fream
b - switch to buffer
0 - delete active
1 - dlete other


M-m move to first non-whitespace char in line !!  (pure gold dust)

syntax table is where word, comment, etc. are defined.
C-h s

subword-mode - treats CamelCase as separate
superword-mode - treats snake_case as one word. 

C-M-f forward sexp, -b backward

C-M-d, u : down into list, up out of list
C-M-k kill sexp in front of point 
C-M-n, p move amongst balanced expressions at the same level

M-{} forward/backward paragraph
M-a/e sentence

C-M-a/e - begin/end function
